microblog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # a list of posts. e.g. /blog/
    url(r'^$', views.PostListView.as_view(), name='post_list'),

    # detail of a post. e.g. /blog/2016/09-19/who-was-django-reinhardt/
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),

    # Share a post via email. e.g. /blog/2/share/
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

microblog/microblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

microblog/blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status=Post.STATUS_PUBLISHED)


class Post(models.Model):

    objects = models.Manager()
    published = PublishedManager()

    STATUS_DRAFT = 'draft'
    STATUS_PUBLISHED = 'published'

    STATUS_CHOICES = (
        (STATUS_DRAFT, 'Draft'),
        (STATUS_PUBLISHED, 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='published_time')
    author = models.ForeignKey(User,
                               related_name='blog_posts')
    body = models.TextField()
    published_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(auto_now=True)
    updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default=STATUS_DRAFT)

    class Meta:
        ordering = ('-published_time',)

    def __str__(self):
        return self.title

    '''
    Returns the canonical URL of the object.
    '''
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.published_time.year,
                           self.published_time.strftime('%m'),
                           self.published_time.strftime('%d'),
                           self.slug
                       ])

microblog/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    review = forms.CharField(required=False,
                             widget=forms.Textarea)

microblog/blog/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.generic import ListView
from smtplib import SMTPException

from .forms import EmailPostForm
from .models import Post


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'page'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status=Post.STATUS_PUBLISHED,
                             published_time__year=year,
                             published_time__month=month,
                             published_time__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})


def mail_delivered(subject, message, sender, receivers):
    try:
        send_mail(subject, message, sender, receivers, fail_silently=False)
    except SMTPException:
        return False
    else:
        return True


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.STATUS_PUBLISHED)
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                form_data['name'], form_data['email'], post.title
            )
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, form_data['name'], form_data['review']
            )
            sender = settings.EMAIL_HOST_USER
            receivers = [form_data['to']]
            if mail_delivered(subject, message, sender, receivers):
                print('mail is delivered')
                template = 'blog/post/share_sent_succeed.html'
                context = {
                    'post': post,
                    'form_data': form_data,
                }
                return render(request, template, context)
            else:
                print('mail not delivered')
                template = 'blog/post/share_sent_failed.html'
                context = {
                    'post': post,
                    'form': form,
                    'error_msg': 'SMTPException',
                }
                return render(request, template, context)
        else:
            template = 'blog/post/share_to_send.html'
            context = {
                'post': post,
                'form': form,
            }
            return render(request, template, context)
    else:
        template = 'blog/post/share_to_send.html'
        form = EmailPostForm()
        context = {
            'post': post,
            'form': form,
        }
        return render(request, template, context)

microblog/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static "css/blog.css" %}">
    </head>
    <body>
        <div id="content">
            {% block content%}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>Xuyan's blog</h2>
            <p>This is Xuyan's blog.</p>
        </div>
    </body>
</html>

microblog/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.published_time }} by {{ post.author }}
    </p>
    {{ post.body | linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>
{% endblock %}

microblog/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Xuyan's Blog{% endblock %}

{% block content %}
    <h1>Xuyan's Blog</h1>
    {% for post in page %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.published_time }} by {{ post.author }}
        </p>
        {{ post.body | truncatewords:30 | linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

microblog/blog/templates/blog/post/share_sent_failed.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    <h1>Share "{{ post.title }}" by email</h1>
    <p>
        Fail to send email due to {{ error_msg }}
    </p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send email">
    </form>
{% endblock %}

microblog/blog/templates/blog/post/share_sent_succeed.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    <h1>E-mail successfully sent</h1>
    <p>
        "{{ post.title }}" was successfully sent to {{ form_data.to }}
    </p>
{% endblock %}

microblog/blog/templates/blog/post/share_to_send.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    <h1>Share "{{ post.title }}" by email</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send email">
    </form>
{% endblock %}

microblog/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span>
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>